"""A whole quest definition."""

# Fields SPT looks up in the locale file, as "<quest id> <field>"
LOCALE_FIELDS = (
	"name",
	"note",
	"acceptPlayerMessage",
	"changeQuestMessageText",
	"completePlayerMessage",
	"declinePlayerMessage",
	"description",
	"failMessageText",
	"startedMessageText",
	"successMessageText",
)


def quest(
	quest_id,
	*,
	name,
	can_show_notifications,
	finish_conditions,
	start_conditions,
	fail_conditions,
	image,
	instant_complete,
	location,
	restartable,
	rewards,
	secret_quest,
	side,
	trader_id,
	quest_type,
):
	"""Returns the quest dict (to be stored under its own id). Text fields are locale keys."""
	return {
		"QuestName": name,
		"_id": quest_id,
		"acceptPlayerMessage": quest_id + " acceptPlayerMessage",
		"acceptanceAndFinishingSource": "eft",
		"arenaLocations": [],
		"canShowNotificationsInGame": can_show_notifications,
		"changeQuestMessageText": quest_id + " changeQuestMessageText",
		"completePlayerMessage": quest_id + " completePlayerMessage",
		"conditions": {
			"AvailableForFinish": finish_conditions,
			"AvailableForStart": start_conditions,
			"Fail": fail_conditions,
		},
		"declinePlayerMessage": quest_id + " declinePlayerMessage",
		"description": quest_id + " description",
		"failMessageText": quest_id + " failMessageText",
		"image": image,
		"instantComplete": instant_complete,
		"isKey": False,
		"location": location,
		"name": quest_id + " name",
		"note": quest_id + " note",
		"progressSource": "eft",
		"rankingModes": [],
		"restartable": restartable,
		"rewards": rewards,
		"secretQuest": secret_quest,
		"side": side,
		"startedMessageText": quest_id + " startedMessageText",
		"successMessageText": quest_id + " successMessageText",
		"traderId": trader_id,
		"type": quest_type,
	}
