# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QTabWidget, QVBoxLayout, QWidget)

class Ui_MainWindowForm(object):
    def setupUi(self, MainWindowForm):
        if not MainWindowForm.objectName():
            MainWindowForm.setObjectName(u"MainWindowForm")
        MainWindowForm.resize(1100, 700)
        self.actionNewQuests = QAction(MainWindowForm)
        self.actionNewQuests.setObjectName(u"actionNewQuests")
        self.actionOpenQuests = QAction(MainWindowForm)
        self.actionOpenQuests.setObjectName(u"actionOpenQuests")
        self.actionImportQuests = QAction(MainWindowForm)
        self.actionImportQuests.setObjectName(u"actionImportQuests")
        self.actionSaveQuests = QAction(MainWindowForm)
        self.actionSaveQuests.setObjectName(u"actionSaveQuests")
        self.actionSaveQuestsAs = QAction(MainWindowForm)
        self.actionSaveQuestsAs.setObjectName(u"actionSaveQuestsAs")
        self.actionNewLocale = QAction(MainWindowForm)
        self.actionNewLocale.setObjectName(u"actionNewLocale")
        self.actionOpenLocale = QAction(MainWindowForm)
        self.actionOpenLocale.setObjectName(u"actionOpenLocale")
        self.actionImportLocale = QAction(MainWindowForm)
        self.actionImportLocale.setObjectName(u"actionImportLocale")
        self.actionSaveLocale = QAction(MainWindowForm)
        self.actionSaveLocale.setObjectName(u"actionSaveLocale")
        self.actionSaveLocaleAs = QAction(MainWindowForm)
        self.actionSaveLocaleAs.setObjectName(u"actionSaveLocaleAs")
        self.actionAssortNew = QAction(MainWindowForm)
        self.actionAssortNew.setObjectName(u"actionAssortNew")
        self.actionAssortOpen = QAction(MainWindowForm)
        self.actionAssortOpen.setObjectName(u"actionAssortOpen")
        self.actionAssortImport = QAction(MainWindowForm)
        self.actionAssortImport.setObjectName(u"actionAssortImport")
        self.actionAssortSave = QAction(MainWindowForm)
        self.actionAssortSave.setObjectName(u"actionAssortSave")
        self.actionAssortSaveAs = QAction(MainWindowForm)
        self.actionAssortSaveAs.setObjectName(u"actionAssortSaveAs")
        self.actionLocksNew = QAction(MainWindowForm)
        self.actionLocksNew.setObjectName(u"actionLocksNew")
        self.actionLocksOpen = QAction(MainWindowForm)
        self.actionLocksOpen.setObjectName(u"actionLocksOpen")
        self.actionLocksImport = QAction(MainWindowForm)
        self.actionLocksImport.setObjectName(u"actionLocksImport")
        self.actionLocksSave = QAction(MainWindowForm)
        self.actionLocksSave.setObjectName(u"actionLocksSave")
        self.actionLocksSaveAs = QAction(MainWindowForm)
        self.actionLocksSaveAs.setObjectName(u"actionLocksSaveAs")
        self.actionAddReferences = QAction(MainWindowForm)
        self.actionAddReferences.setObjectName(u"actionAddReferences")
        self.actionManageReferences = QAction(MainWindowForm)
        self.actionManageReferences.setObjectName(u"actionManageReferences")
        self.actionReloadReferences = QAction(MainWindowForm)
        self.actionReloadReferences.setObjectName(u"actionReloadReferences")
        self.actionImportFiles = QAction(MainWindowForm)
        self.actionImportFiles.setObjectName(u"actionImportFiles")
        self.actionExportQuests = QAction(MainWindowForm)
        self.actionExportQuests.setObjectName(u"actionExportQuests")
        self.actionExit = QAction(MainWindowForm)
        self.actionExit.setObjectName(u"actionExit")
        self.actionUndo = QAction(MainWindowForm)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindowForm)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionSettings = QAction(MainWindowForm)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionAbout = QAction(MainWindowForm)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionRegenerateAssort = QAction(MainWindowForm)
        self.actionRegenerateAssort.setObjectName(u"actionRegenerateAssort")
        self.actionRegenerateLocks = QAction(MainWindowForm)
        self.actionRegenerateLocks.setObjectName(u"actionRegenerateLocks")
        self.actionUpdates = QAction(MainWindowForm)
        self.actionUpdates.setObjectName(u"actionUpdates")
        self.centralwidget = QWidget(MainWindowForm)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralLayout = QVBoxLayout(self.centralwidget)
        self.centralLayout.setSpacing(0)
        self.centralLayout.setObjectName(u"centralLayout")
        self.centralLayout.setContentsMargins(0, 0, 0, 0)
        self.tabs = QTabWidget(self.centralwidget)
        self.tabs.setObjectName(u"tabs")
        self.page_quests = QWidget()
        self.page_quests.setObjectName(u"page_quests")
        self.tabs.addTab(self.page_quests, "")
        self.page_locale = QWidget()
        self.page_locale.setObjectName(u"page_locale")
        self.tabs.addTab(self.page_locale, "")
        self.page_trader = QWidget()
        self.page_trader.setObjectName(u"page_trader")
        self.tabs.addTab(self.page_trader, "")
        self.page_composite = QWidget()
        self.page_composite.setObjectName(u"page_composite")
        self.tabs.addTab(self.page_composite, "")
        self.page_find_ids = QWidget()
        self.page_find_ids.setObjectName(u"page_find_ids")
        self.tabs.addTab(self.page_find_ids, "")
        self.page_explorer = QWidget()
        self.page_explorer.setObjectName(u"page_explorer")
        self.tabs.addTab(self.page_explorer, "")

        self.centralLayout.addWidget(self.tabs)

        MainWindowForm.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindowForm)
        self.menubar.setObjectName(u"menubar")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuQuests = QMenu(self.menuFile)
        self.menuQuests.setObjectName(u"menuQuests")
        self.menuLocale = QMenu(self.menuFile)
        self.menuLocale.setObjectName(u"menuLocale")
        self.menuAssort = QMenu(self.menuFile)
        self.menuAssort.setObjectName(u"menuAssort")
        self.menuLocks = QMenu(self.menuFile)
        self.menuLocks.setObjectName(u"menuLocks")
        self.menuReferences = QMenu(self.menuFile)
        self.menuReferences.setObjectName(u"menuReferences")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuDebug = QMenu(self.menubar)
        self.menuDebug.setObjectName(u"menuDebug")
        MainWindowForm.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.menuFile.addAction(self.actionImportFiles)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuQuests.menuAction())
        self.menuFile.addAction(self.menuLocale.menuAction())
        self.menuFile.addAction(self.menuAssort.menuAction())
        self.menuFile.addAction(self.menuLocks.menuAction())
        self.menuFile.addAction(self.menuReferences.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuQuests.addAction(self.actionNewQuests)
        self.menuQuests.addAction(self.actionOpenQuests)
        self.menuQuests.addAction(self.actionImportQuests)
        self.menuQuests.addSeparator()
        self.menuQuests.addAction(self.actionSaveQuests)
        self.menuQuests.addAction(self.actionSaveQuestsAs)
        self.menuQuests.addSeparator()
        self.menuQuests.addAction(self.actionExportQuests)
        self.menuLocale.addAction(self.actionNewLocale)
        self.menuLocale.addAction(self.actionOpenLocale)
        self.menuLocale.addAction(self.actionImportLocale)
        self.menuLocale.addSeparator()
        self.menuLocale.addAction(self.actionSaveLocale)
        self.menuLocale.addAction(self.actionSaveLocaleAs)
        self.menuAssort.addAction(self.actionAssortNew)
        self.menuAssort.addAction(self.actionAssortOpen)
        self.menuAssort.addAction(self.actionAssortImport)
        self.menuAssort.addSeparator()
        self.menuAssort.addAction(self.actionAssortSave)
        self.menuAssort.addAction(self.actionAssortSaveAs)
        self.menuLocks.addAction(self.actionLocksNew)
        self.menuLocks.addAction(self.actionLocksOpen)
        self.menuLocks.addAction(self.actionLocksImport)
        self.menuLocks.addSeparator()
        self.menuLocks.addAction(self.actionLocksSave)
        self.menuLocks.addAction(self.actionLocksSaveAs)
        self.menuReferences.addAction(self.actionAddReferences)
        self.menuReferences.addAction(self.actionManageReferences)
        self.menuReferences.addAction(self.actionReloadReferences)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuSettings.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionUpdates)
        self.menuDebug.addAction(self.actionRegenerateAssort)
        self.menuDebug.addAction(self.actionRegenerateLocks)

        self.retranslateUi(MainWindowForm)

        self.tabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindowForm)
    # setupUi

    def retranslateUi(self, MainWindowForm):
        MainWindowForm.setWindowTitle(QCoreApplication.translate("MainWindowForm", u"SPT Trader Builder", None))
        self.actionNewQuests.setText(QCoreApplication.translate("MainWindowForm", u"New (empty)", None))
#if QT_CONFIG(shortcut)
        self.actionNewQuests.setShortcut(QCoreApplication.translate("MainWindowForm", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenQuests.setText(QCoreApplication.translate("MainWindowForm", u"Open...", None))
#if QT_CONFIG(shortcut)
        self.actionOpenQuests.setShortcut(QCoreApplication.translate("MainWindowForm", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionImportQuests.setText(QCoreApplication.translate("MainWindowForm", u"Import...", None))
        self.actionSaveQuests.setText(QCoreApplication.translate("MainWindowForm", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSaveQuests.setShortcut(QCoreApplication.translate("MainWindowForm", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveQuestsAs.setText(QCoreApplication.translate("MainWindowForm", u"Save as...", None))
#if QT_CONFIG(shortcut)
        self.actionSaveQuestsAs.setShortcut(QCoreApplication.translate("MainWindowForm", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionNewLocale.setText(QCoreApplication.translate("MainWindowForm", u"New (empty)", None))
        self.actionOpenLocale.setText(QCoreApplication.translate("MainWindowForm", u"Open...", None))
        self.actionImportLocale.setText(QCoreApplication.translate("MainWindowForm", u"Import...", None))
        self.actionSaveLocale.setText(QCoreApplication.translate("MainWindowForm", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSaveLocale.setShortcut(QCoreApplication.translate("MainWindowForm", u"Ctrl+Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveLocaleAs.setText(QCoreApplication.translate("MainWindowForm", u"Save as...", None))
        self.actionAssortNew.setText(QCoreApplication.translate("MainWindowForm", u"New (empty)", None))
        self.actionAssortOpen.setText(QCoreApplication.translate("MainWindowForm", u"Open...", None))
        self.actionAssortImport.setText(QCoreApplication.translate("MainWindowForm", u"Import...", None))
        self.actionAssortSave.setText(QCoreApplication.translate("MainWindowForm", u"Save", None))
        self.actionAssortSaveAs.setText(QCoreApplication.translate("MainWindowForm", u"Save as...", None))
        self.actionLocksNew.setText(QCoreApplication.translate("MainWindowForm", u"New (empty)", None))
        self.actionLocksOpen.setText(QCoreApplication.translate("MainWindowForm", u"Open...", None))
        self.actionLocksImport.setText(QCoreApplication.translate("MainWindowForm", u"Import...", None))
        self.actionLocksSave.setText(QCoreApplication.translate("MainWindowForm", u"Save", None))
        self.actionLocksSaveAs.setText(QCoreApplication.translate("MainWindowForm", u"Save as...", None))
        self.actionAddReferences.setText(QCoreApplication.translate("MainWindowForm", u"&Add reference files...", None))
#if QT_CONFIG(tooltip)
        self.actionAddReferences.setToolTip(QCoreApplication.translate("MainWindowForm", u"Files that are only looked at (other mods' quests, items, traders), never edited or saved", None))
#endif // QT_CONFIG(tooltip)
        self.actionManageReferences.setText(QCoreApplication.translate("MainWindowForm", u"&Manage reference files...", None))
#if QT_CONFIG(tooltip)
        self.actionManageReferences.setToolTip(QCoreApplication.translate("MainWindowForm", u"See, remove or reload the reference files", None))
#endif // QT_CONFIG(tooltip)
        self.actionReloadReferences.setText(QCoreApplication.translate("MainWindowForm", u"&Reload reference files", None))
#if QT_CONFIG(tooltip)
        self.actionReloadReferences.setToolTip(QCoreApplication.translate("MainWindowForm", u"Read the reference files again", None))
#endif // QT_CONFIG(tooltip)
        self.actionImportFiles.setText(QCoreApplication.translate("MainWindowForm", u"&Import files...", None))
#if QT_CONFIG(shortcut)
        self.actionImportFiles.setShortcut(QCoreApplication.translate("MainWindowForm", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionExportQuests.setText(QCoreApplication.translate("MainWindowForm", u"&Export selected quests...", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindowForm", u"E&xit", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindowForm", u"Alt+F4", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindowForm", u"&Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindowForm", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindowForm", u"&Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindowForm", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionSettings.setText(QCoreApplication.translate("MainWindowForm", u"&Settings...", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindowForm", u"&About", None))
        self.actionRegenerateAssort.setText(QCoreApplication.translate("MainWindowForm", u"Regenerate trader assort using known data...", None))
#if QT_CONFIG(tooltip)
        self.actionRegenerateAssort.setToolTip(QCoreApplication.translate("MainWindowForm", u"Save a new trader assort file made only from the offers the program knows: their items, prices and levels", None))
#endif // QT_CONFIG(tooltip)
        self.actionRegenerateLocks.setText(QCoreApplication.translate("MainWindowForm", u"Regenerate quest assort using known data...", None))
#if QT_CONFIG(tooltip)
        self.actionRegenerateLocks.setToolTip(QCoreApplication.translate("MainWindowForm", u"Save a new quest assort file with only the links to offers and quests the program knows", None))
#endif // QT_CONFIG(tooltip)
        self.actionUpdates.setText(QCoreApplication.translate("MainWindowForm", u"Check for &updates", None))
        self.tabs.setTabText(self.tabs.indexOf(self.page_quests), QCoreApplication.translate("MainWindowForm", u"Quests", None))
        self.tabs.setTabText(self.tabs.indexOf(self.page_locale), QCoreApplication.translate("MainWindowForm", u"Locale", None))
        self.tabs.setTabText(self.tabs.indexOf(self.page_trader), QCoreApplication.translate("MainWindowForm", u"Trader", None))
        self.tabs.setTabText(self.tabs.indexOf(self.page_composite), QCoreApplication.translate("MainWindowForm", u"Composite items", None))
        self.tabs.setTabText(self.tabs.indexOf(self.page_find_ids), QCoreApplication.translate("MainWindowForm", u"Find IDs", None))
        self.tabs.setTabText(self.tabs.indexOf(self.page_explorer), QCoreApplication.translate("MainWindowForm", u"Schema Explorer", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindowForm", u"&File", None))
        self.menuQuests.setTitle(QCoreApplication.translate("MainWindowForm", u"&Quests", None))
        self.menuLocale.setTitle(QCoreApplication.translate("MainWindowForm", u"&Locale", None))
        self.menuAssort.setTitle(QCoreApplication.translate("MainWindowForm", u"&Trader assort", None))
        self.menuLocks.setTitle(QCoreApplication.translate("MainWindowForm", u"Quest &assort", None))
        self.menuReferences.setTitle(QCoreApplication.translate("MainWindowForm", u"&References", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindowForm", u"&Edit", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindowForm", u"&Settings", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindowForm", u"&Help", None))
        self.menuDebug.setTitle(QCoreApplication.translate("MainWindowForm", u"&Debug", None))
    # retranslateUi

