# Form implementation generated from reading ui file 'tb_ui\gui_datafiles.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DataEditor(object):
	def setupUi(self, DataEditor):
		DataEditor.setObjectName("DataEditor")
		DataEditor.resize(676, 449)
		self.centralwidget = QtWidgets.QWidget(parent=DataEditor)
		self.centralwidget.setObjectName("centralwidget")
		self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
		self.tabWidget.setGeometry(QtCore.QRect(0, 0, 661, 401))
		self.tabWidget.setObjectName("tabWidget")
		self.tab_3 = QtWidgets.QWidget()
		self.tab_3.setObjectName("tab_3")
		self.pb_wtt_import = QtWidgets.QPushButton(parent=self.tab_3)
		self.pb_wtt_import.setGeometry(QtCore.QRect(10, 70, 75, 24))
		self.pb_wtt_import.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
		self.pb_wtt_import.setObjectName("pb_wtt_import")
		self.label_3 = QtWidgets.QLabel(parent=self.tab_3)
		self.label_3.setGeometry(QtCore.QRect(10, 10, 351, 51))
		self.label_3.setWordWrap(True)
		self.label_3.setObjectName("label_3")
		self.tabWidget.addTab(self.tab_3, "")
		DataEditor.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(parent=DataEditor)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 22))
		self.menubar.setObjectName("menubar")
		DataEditor.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(parent=DataEditor)
		self.statusbar.setObjectName("statusbar")
		DataEditor.setStatusBar(self.statusbar)

		self.retranslateUi(DataEditor)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(DataEditor)

	def retranslateUi(self, DataEditor):
		_translate = QtCore.QCoreApplication.translate
		DataEditor.setWindowTitle(_translate("DataEditor", "Data File Editor"))
		self.pb_wtt_import.setText(_translate("DataEditor", "Import"))
		self.label_3.setText(
			_translate(
				"DataEditor",
				"If using WTTCommonLib, you can use this to import all valid files. Select the top-level folder in the structure.",
			)
		)
		self.tabWidget.setTabText(
			self.tabWidget.indexOf(self.tab_3),
			_translate("DataEditor", "WTTCommonLib Settings"),
		)
