# Form implementation generated from reading ui file 'gui_tasks.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TaskWindow(object):
    def setupUi(self, TaskWindow):
        TaskWindow.setObjectName("TaskWindow")
        TaskWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=TaskWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_elim = QtWidgets.QWidget()
        self.tab_elim.setObjectName("tab_elim")
        self.tabWidget.addTab(self.tab_elim, "")
        self.tab_handover_item = QtWidgets.QWidget()
        self.tab_handover_item.setObjectName("tab_handover_item")
        self.tabWidget.addTab(self.tab_handover_item, "")
        self.tab_visit_zone = QtWidgets.QWidget()
        self.tab_visit_zone.setObjectName("tab_visit_zone")
        self.tabWidget.addTab(self.tab_visit_zone, "")
        self.tab_leave_item = QtWidgets.QWidget()
        self.tab_leave_item.setObjectName("tab_leave_item")
        self.tabWidget.addTab(self.tab_leave_item, "")
        TaskWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=TaskWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        TaskWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=TaskWindow)
        self.statusbar.setObjectName("statusbar")
        TaskWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TaskWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TaskWindow)

    def retranslateUi(self, TaskWindow):
        _translate = QtCore.QCoreApplication.translate
        TaskWindow.setWindowTitle(_translate("TaskWindow", "Task Builder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_elim), _translate("TaskWindow", "Elimination"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_handover_item), _translate("TaskWindow", "Hand Over/Find Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_visit_zone), _translate("TaskWindow", "Visit Zone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_leave_item), _translate("TaskWindow", "Leave Item At Location"))
