pyside6-uic -o tb_ui\gui_main.py tb_ui\gui_main.ui
pyside6-uic -o tb_ui\gui_about.py tb_ui\gui_about.ui
pyside6-uic -o tb_ui\gui_updates.py tb_ui\gui_updates.ui
pyside6-uic -o tb_ui\gui_quests.py tb_ui\gui_quests.ui
pyside6-uic -o tb_ui\gui_tasks.py tb_ui\gui_tasks.ui
pyside6-uic -o tb_ui\gui_assort.py tb_ui\gui_assort.ui
pyside6-uic -o tb_ui\gui_rewards.py tb_ui\gui_rewards.ui
pyside6-uic -o tb_ui\gui_datafiles.py tb_ui\gui_datafiles.ui
pyside6-uic -o tb_ui\gui_settings.py tb_ui\gui_settings.ui